# install.packages("https://cran.r-project.org/src/contrib/Archive/LOGIT/LOGIT_1.3.tar.gz", repos=NULL, type="source")
# hoeffding correlation coefficient SAS monotonic
default:
  seed: 2019
  n_resampling: 10 
  print: TRUE
  settings:
    data_folder: "data"
    images_folder: "figures/"
    libraries: !expr c(
        "tidyverse",
        "caret",
        "sf",
        "pROC",
        "data.table",
        "latticeExtra",
        "cowplot",
        "sjPlot",
        "LOGIT",
        "expss"
      )
    github: !expr c(
        "UrbanInstitute/urbnmapr"
      )
    sources: !expr c()
  algorithms: !expr list(
      "glm" = "Logistic Regression",
      "svm" = "SVM",
      "rf" = "Random Forest"
    )
  predictors:
    parties_levels: !expr c("no", "yes")
    list: !expr list(
        "pop_14" = list(
          "name" = "Population estimates (2014)",
          "orig" = "Population estimates",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Population"
        ),
        "pop_foreign_pct_13" = list(
          "name" = "% of foreign born persons",
          "orig" = "Foreign born persons, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Population Characteristics"
        ),
        "age_o65_pct_14" = list(
          "name" = "% of persons 65 years and over",
          "orig" = "Persons 65 years and over, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Age and Sex"
        ),
        "edu_bach_pct_13" = list(
          "name" = "% of persons age 25 years+ with bachelor's degree or higher",
          "orig" = "Bachelor's degree or higher, percent of persons age 25 years+",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Education"
        ),
        "hsg_val_units_13" = list(
          "name" = "Median value of owner-occupied housing units, ($1,000)",
          "orig" = "Median value of owner-occupied housing units",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Housing"
        ),
        "hsg_multiunit_pct_13" = list(
          "name" = "% of housing units in multi-unit structures",
          "orig" = "Housing units in multi-unit structures, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Housing"
        ),
        "hsg_homeowner_rate_13" = list(
          "name" = "Owner-occupied housing unit rate",
          "orig" = "Owner-occupied housing unit rate",
          "plots" = list(
            "density" = c(0.2, 0.85)
          ),
          "group" = "Housing"
        ),
        "rh_white_nohisp_pct_14" = list(
          "name" = "% of White alone, not Hispanic or Latino",
          "orig" = "White alone, not Hispanic or Latino, percent",
          "plots" = list(
            "density" = c(0.2, 0.85)
          ),
          "group" = "Race and Hispanic Origin"
        ),
        "rh_latino_pct_14" = list(
          "name" = "% of Hispanic or Latino",
          "orig" = "Hispanic or Latino, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Race and Hispanic Origin"
        ),
        "rh_asian_pct_14" = list(
          "name" = "% of Asian alone",
          "orig" = "Asian alone, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Race and Hispanic Origin"
        ),
        "rh_afroamerican_pct_14" = list(
          "name" = "% of Black or African American alone",
          "orig" = "Black or African American alone, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Race and Hispanic Origin"
        ),
        "inc_pc_12_month_13" = list(
          "name" = "Per capita income in past 12 months",
          "orig" = "Per capita income in past 12 months",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Income"
        ),
        "firms_rate_07" = list(
          "name" = "Firms rate",
          "orig" = "Firms",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Businesses"
        ),
        "veterans_pct_13" = list(
          "name" = "% of veterans",
          "orig" = "Veterans, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Population Characteristics"
        ),
        "females_pct_14" = list(
          "name" = "% of female persons",
          "orig" = "Female persons, percent",
          "plots" = list(
            "density" = c(0.8, 0.85)
          ),
          "group" = "Age and Sex"
        )
      )
  theme:
    font_family: "Arial"
    font_color: "#4e4d47"
    bg_color: "#f5f5f2"
    border_color: "#e8e8e5"
    # https://davidmathlogic.com/colorblind/
    plots: !expr c("#D81B1B", "#1E88E5", "#FFC107", "#025446")
    parties_colors: !expr c("#105099", "#d93334")
    parties_factors: !expr c("no", "yes")
    parties_labels: !expr c("Hillary Clinton", "Donald Trump")
    # library(RColorBrewer)
    # brewer.pal(n=10, name="RdYlBu")
    # caching...
    correlations: !expr c(
        "#A50026", "#D73027", 
        "#F46D43", "#FDAE61", 
        "#FEE090", "#E0F3F8", 
        "#ABD9E9", "#74ADD1", 
        "#4575B4", "#313695"
      )

